# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:7.8.0

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches"
  branches:
    master:
      - step:
          script:
            - npm install -g firebase-tools
            - npm install
            - npm run build
            - firebase deploy --token "$FIREBASE_TOKEN"
